server:
  port: 8888

spring:
  profiles:
    active: ${CLOUD_PROFILES:native}
  security:
    user:
      name: ${CLOUND_ADMIN_NAME:ADMIN}
      password: ${CLOUND_ADMIN_PASSWORD:ADMIN}
  cloud:
    config:
      server:
        native:
          search-locations: ${CLOUD_SEARCH_LOCATIONS:~/properties}

encrypt:
  key: ${INSIDE_CLOUD_KEY:foM}kcGHmxB7[C9}
